### ISSUE TITLE
Create graphics for ending background

### ISSUE THREAD

**Issue by StaNov** [StaNov/LoadingGame#27]
* Loading/Assets/Images/EndingBackgroundAchieved.png
* Loading/Assets/Images/EndingBackgroundNotAchieved.png

![](https://raw.githubusercontent.com/StaNov/LoadingGame/master/Loading/Assets/Images/EndingBackgroundAchieved.png)

![](https://raw.githubusercontent.com/StaNov/LoadingGame/master/Loading/Assets/Images/EndingBackgroundNotAchieved.png)

**Comment by bitsofstring** [comment]
Can you explain a little more what exactly this is?
Is this the screen that the "play again" button will show up on?

**Comment by StaNov** [comment]
> Is this the screen that the "play again" button will show up on?

Yes, exactly. Play the latest version and you'll see :) It's in the endScreen scene.

**Comment by StaNov** [comment]
Good job, closing issue.
