### ISSUE TITLE
Check grammar

### ISSUE THREAD

**Issue by StaNov** [StaNov/LoadingGame#86]

**Comment by bitsofstring** [comment]
"Just wait a second, ok?" 
to
"Just wait a second, okay?"

**Comment by bitsofstring** [comment]
"Okay okay, I'm going out, okay?!"
to
"Okay, okay... I'm coming out, okay?!"

**Comment by bitsofstring** [comment]
Actually, using "okay" 3 times in one sentence sounds a little weird. 
Maybe change:
"Okay okay, I'm going out, okay?!"
to
"Fine... I'm coming out, okay?!"
